### ISSUE TITLE
Pagination is buggy sometimes on the first run

### ISSUE THREAD

**Issue by brytonmoeller** [makeroots/makeroots.github.io#10]
Video of bug: https://drive.google.com/file/d/1ZtKmUjhW1iTtm1D89_rXtZFkjh-SBxnd/view?usp=sharing
Lucy and Carly are ok with having it not paginate if this is hard to fix.

**Comment by ALowVerus** [comment]
Lies. I fail to see the issue.

**Comment by ALowVerus** [comment]
I need access to one of the error-prone browsers before I can figure out what's wrong.
