### ISSUE TITLE
Update Text and Formatting to Match Template

### ISSUE THREAD

**Issue by makeroots** [makeroots/makeroots.github.io#3]

**Comment by makeroots** [comment]
I will handle the text, I can do that!

**Comment by ALowVerus** [comment]
I can't really do much more here until text is added.

**Comment by ALowVerus** [comment]
Made most changes. Just need to fix up navbar and fonts, I think.

**Comment by ALowVerus** [comment]
Okay, not sure I'm going to be able to get the exact font - I'm having trouble integrating into Jekyll. Arial looks close enough for now, I think.
